In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_url = "./data/credit-a.csv"

In [3]:
data = pd.read_csv(data_url,header=None)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653 entries, 0 to 652
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       653 non-null    int64  
 1   1       653 non-null    float64
 2   2       653 non-null    float64
 3   3       653 non-null    int64  
 4   4       653 non-null    int64  
 5   5       653 non-null    int64  
 6   6       653 non-null    int64  
 7   7       653 non-null    float64
 8   8       653 non-null    int64  
 9   9       653 non-null    int64  
 10  10      653 non-null    int64  
 11  11      653 non-null    int64  
 12  12      653 non-null    int64  
 13  13      653 non-null    int64  
 14  14      653 non-null    float64
 15  15      653 non-null    int64  
dtypes: float64(4), int64(12)
memory usage: 81.8 KB


In [5]:
data.head()

0      1      2   3   4   5   6     7   8   9   10  11  12   13     14  15
0   0  30.83  0.000   0   0   9   0  1.25   0   0   1   1   0  202    0.0  -1
1   1  58.67  4.460   0   0   8   1  3.04   0   0   6   1   0   43  560.0  -1
2   1  24.50  0.500   0   0   8   1  1.50   0   1   0   1   0  280  824.0  -1
3   0  27.83  1.540   0   0   9   0  3.75   0   0   5   0   0  100    3.0  -1
4   0  20.17  5.625   0   0   9   0  1.71   0   1   0   1   2  120    0.0  -1

In [6]:
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]

In [7]:
Y

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
648    1
649    1
650    1
651    1
652    1
Name: 15, Length: 653, dtype: int64

In [8]:
Y.unique()

array([-1,  1], dtype=int64)

In [9]:
Y = data.iloc[:,-1].replace(-1,0)

In [10]:
Y.unique()

array([0, 1], dtype=int64)

In [11]:
#转换为tensor
X = torch.from_numpy(X.values).type(torch.float32)
Y = torch.from_numpy(Y.values.reshape(-1,1)).type(torch.float32)

In [12]:
X.shape

torch.Size([653, 15])

In [13]:
Y.shape

torch.Size([653, 1])

In [14]:
from torch import nn

In [15]:
model = nn.Sequential(
    nn.Linear(15,1),
    nn.Sigmoid()
)

In [16]:
model

Sequential(
  (0): Linear(in_features=15, out_features=1, bias=True)
  (1): Sigmoid()
)

In [17]:
loss_fun = nn.BCELoss() #二元交叉熵

In [18]:
opt = torch.optim.Adam(model.parameters(),lr=0.0001)

In [19]:
batch_n = 653//16  #每次取16个

In [20]:
for epoch in range(1000):
    for batch in range(batch_n):
        start = batch * 16
        end = start + 16
        x = X[start:end]
        y = Y[start:end]
        y_pred = model(x)
        loss = loss_fun(y_pred,y)
        #梯度清零
        opt.zero_grad()
        loss.backward()
        opt.step()

In [21]:
model.state_dict()#查看权重

OrderedDict([('0.weight',
              tensor([[-1.6775e-02, -9.5208e-03, -6.9202e-03,  2.7206e-01,  1.2922e-01,
                       -2.2820e-02,  1.9154e-01, -1.6395e-01,  1.8891e+00,  2.8554e-01,
                       -1.9568e-01,  5.0928e-02,  2.3313e-02,  9.8713e-04, -3.3621e-04]])),
             ('0.bias', tensor([0.1699]))])

In [22]:
#查看正确率

In [29]:
model(X).data.numpy()

array([[3.82408649e-01],
       [1.00219600e-01],
       [5.03811479e-01],
       [1.41042396e-01],
       [4.88679975e-01],
       [4.82722461e-01],
       [1.29037408e-05],
       [4.41366345e-01],
       [4.71615672e-01],
       [3.23061883e-01],
       [8.90068650e-01],
       [4.69786584e-01],
       [4.39025104e-01],
       [7.04903781e-01],
       [6.13412783e-02],
       [1.67342260e-01],
       [3.55347365e-01],
       [6.41021803e-02],
       [5.75792015e-01],
       [2.15854675e-01],
       [1.72881912e-02],
       [6.18670821e-01],
       [3.74811552e-02],
       [3.14157486e-01],
       [2.70454586e-01],
       [4.26099241e-01],
       [6.43038601e-02],
       [2.67154071e-03],
       [1.01663060e-01],
       [4.93845390e-03],
       [1.06815413e-01],
       [4.09345329e-02],
       [2.73429998e-03],
       [8.60895365e-02],
       [1.74569696e-01],
       [8.51277784e-02],
       [9.38151553e-02],
       [3.66719186e-01],
       [4.91092950e-01],
       [1.87455714e-02],


In [30]:
(model(X).data.numpy() > 0.5).astype(np.int64)

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [28]:
Y

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
      

In [32]:
(model(X).data.numpy() > 0.5).astype(np.int64) == Y.numpy()

array([[ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [

In [34]:
((model(X).data.numpy() > 0.5).astype(np.int64) == Y.numpy()).mean()#0，1数据求平均即可得平均值

0.8652373660030628